// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillsetsBackend.Infrastructure.Persistence;

#nullable disable

namespace SkillsetsBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820130000_AddUserPermissionOverrides")]
    partial class AddUserPermissionOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillsetsBackend.Domain.CourseLibrary.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CourseId"));

                    b.Property<string>("AboutContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AboutContent");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CourseSourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CourseSourceUrl");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CourseTitle");

                    b.Property<string>("CourseUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CourseURL");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Duration");

                    b.Property<string>("ExpertiseLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ExpertiseLevel");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ImageURL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("LaunchUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LaunchURL");

                    b.Property<string>("OverviewContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OverviewContent");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ScrapedAt");

                    b.Property<string>("SkillsoftCourseCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SkillsoftCourseCode");

                    b.Property<string>("SourceStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SourceStatus");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Status");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("SubCategoryID");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.CourseLibrary.CourseSection", b =>
                {
                    b.Property<long>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SectionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SectionId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("CourseID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Duration");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("SectionName");

                    b.Property<string>("SectionUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("SectionURL");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Status");

                    b.HasKey("SectionId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSections", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.CourseLibrary.CourseTaken", b =>
                {
                    b.Property<int>("CourseTakenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseTakenId"));

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CourseTakenId");

                    b.HasIndex("CourseId")
                        .IsUnique()
                        .HasDatabaseName("IX_CourseTakens_ActiveCourse")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_CourseTakens_ActiveUser")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CourseTakens", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.CourseLibrary.LibraryCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CategoryName");

                    b.Property<string>("CategoryUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CategoryURL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("CategoryId");

                    b.ToTable("LibraryCategories", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.CourseLibrary.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SubCategoryName");

                    b.Property<string>("SubCategoryUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("SubCategoryURL");

                    b.HasKey("SubCategoryId");

                    b.ToTable("SubCategories", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LegacyUserId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyPhone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentForm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("PlanEndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateOnly(2099, 12, 31));

                    b.Property<DateOnly>("PlanStartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateOnly(2020, 1, 1));

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("License");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Street2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.LoginActivityLog", b =>
                {
                    b.Property<int>("LoginActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginActivityLogId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginActivityLogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.ToTable("LoginActivityLogs", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionKey")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Category = "Employees",
                            Description = "View Employees",
                            PermissionKey = "Students.View"
                        },
                        new
                        {
                            PermissionId = 2,
                            Category = "Employees",
                            Description = "Create Employees",
                            PermissionKey = "Students.Create"
                        },
                        new
                        {
                            PermissionId = 3,
                            Category = "Employees",
                            Description = "Edit Employees",
                            PermissionKey = "Students.Update"
                        },
                        new
                        {
                            PermissionId = 4,
                            Category = "Employees",
                            Description = "Delete Employees",
                            PermissionKey = "Students.Delete"
                        },
                        new
                        {
                            PermissionId = 5,
                            Category = "Employees",
                            Description = "Reset Employee Password",
                            PermissionKey = "Students.ManagePassword"
                        },
                        new
                        {
                            PermissionId = 6,
                            Category = "Employees",
                            Description = "Assign Employee to a Manager",
                            PermissionKey = "Students.AssignManager"
                        },
                        new
                        {
                            PermissionId = 7,
                            Category = "Employees",
                            Description = "View Employee Login Credentials",
                            PermissionKey = "Students.ViewCredentials"
                        },
                        new
                        {
                            PermissionId = 11,
                            Category = "Managers",
                            Description = "View Managers",
                            PermissionKey = "Managers.View"
                        },
                        new
                        {
                            PermissionId = 12,
                            Category = "Managers",
                            Description = "Create Managers",
                            PermissionKey = "Managers.Create"
                        },
                        new
                        {
                            PermissionId = 13,
                            Category = "Managers",
                            Description = "Edit Managers",
                            PermissionKey = "Managers.Update"
                        },
                        new
                        {
                            PermissionId = 14,
                            Category = "Managers",
                            Description = "Reset Manager Password",
                            PermissionKey = "Managers.ManagePassword"
                        },
                        new
                        {
                            PermissionId = 15,
                            Category = "Managers",
                            Description = "View Manager Login Credentials",
                            PermissionKey = "Managers.ViewCredentials"
                        },
                        new
                        {
                            PermissionId = 21,
                            Category = "Companies",
                            Description = "View Companies",
                            PermissionKey = "Companies.View"
                        },
                        new
                        {
                            PermissionId = 22,
                            Category = "Companies",
                            Description = "Create Companies",
                            PermissionKey = "Companies.Create"
                        },
                        new
                        {
                            PermissionId = 31,
                            Category = "Roles & Permissions",
                            Description = "View Roles & Permissions",
                            PermissionKey = "Roles.View"
                        },
                        new
                        {
                            PermissionId = 32,
                            Category = "Roles & Permissions",
                            Description = "Create & Edit Roles",
                            PermissionKey = "Roles.Manage"
                        },
                        new
                        {
                            PermissionId = 41,
                            Category = "FAQs",
                            Description = "View FAQs",
                            PermissionKey = "Faq.View"
                        },
                        new
                        {
                            PermissionId = 42,
                            Category = "FAQs",
                            Description = "Create FAQs",
                            PermissionKey = "Faq.Create"
                        },
                        new
                        {
                            PermissionId = 43,
                            Category = "FAQs",
                            Description = "Edit FAQs",
                            PermissionKey = "Faq.Update"
                        },
                        new
                        {
                            PermissionId = 44,
                            Category = "FAQs",
                            Description = "Delete FAQs",
                            PermissionKey = "Faq.Delete"
                        },
                        new
                        {
                            PermissionId = 51,
                            Category = "Contact Info",
                            Description = "View Contact Info",
                            PermissionKey = "ContactInfo.View"
                        },
                        new
                        {
                            PermissionId = 52,
                            Category = "Contact Info",
                            Description = "Create Contact Info",
                            PermissionKey = "ContactInfo.Create"
                        },
                        new
                        {
                            PermissionId = 53,
                            Category = "Contact Info",
                            Description = "Edit Contact Info",
                            PermissionKey = "ContactInfo.Update"
                        },
                        new
                        {
                            PermissionId = 54,
                            Category = "Contact Info",
                            Description = "Delete Contact Info",
                            PermissionKey = "ContactInfo.Delete"
                        },
                        new
                        {
                            PermissionId = 61,
                            Category = "System Logs",
                            Description = "View System Logs",
                            PermissionKey = "SystemLogs.View"
                        },
                        new
                        {
                            PermissionId = 71,
                            Category = "Course Library",
                            Description = "View Course Library",
                            PermissionKey = "CourseLibrary.View"
                        },
                        new
                        {
                            PermissionId = 72,
                            Category = "Course Library",
                            Description = "Publish Courses",
                            PermissionKey = "CourseLibrary.Publish"
                        },
                        new
                        {
                            PermissionId = 81,
                            Category = "Course Provider",
                            Description = "Launch Courses",
                            PermissionKey = "Skillsoft.LaunchCourse"
                        },
                        new
                        {
                            PermissionId = 82,
                            Category = "Course Provider",
                            Description = "View Learning Transcript",
                            PermissionKey = "Skillsoft.ViewTranscript"
                        },
                        new
                        {
                            PermissionId = 83,
                            Category = "Course Provider",
                            Description = "View Course Catalog",
                            PermissionKey = "Skillsoft.ViewCatalog"
                        });
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.Role", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.RolePermission", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 71
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 81
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 82
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 83
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 52
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 54
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 71
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 81
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 82
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 83
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 52
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 54
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 71
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 81
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 82
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 83
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 52
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 54
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 71
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 72
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 81
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 82
                        },
                        new
                        {
                            RoleId = (byte)5,
                            PermissionId = 83
                        });
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.UserPermissionOverride", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissionOverrides", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.StudentProfile", b =>
                {
                    b.Property<int>("StudentProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentProfileId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("StudentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentProfileId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.UserCompanyRole", b =>
                {
                    b.Property<int>("UserCompanyRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCompanyRoleId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserCompanyRoleId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompanyRoles", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.UserCredential", b =>
                {
                    b.Property<long>("UserCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserCredentialId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserCredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Skillsoft.ActiveLibraryCard", b =>
                {
                    b.Property<int>("ActiveLibraryCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActiveLibraryCardId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActiveLibraryCardId"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Company_Code");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Company_Name");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("End_Date");

                    b.Property<string>("FdmName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FDM_Name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("ManagerId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Manager_ID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Password");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start_Date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("User_ID");

                    b.HasKey("ActiveLibraryCardId");

                    b.ToTable("ActiveLibraryCards", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Skillsoft.SkillportSession", b =>
                {
                    b.Property<int>("SkillportSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillportSessionId"));

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("SkillportPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SkillportUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SkillportSessionId");

                    b.HasIndex("UserId", "CompanyId");

                    b.ToTable("SkillportSessions", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Support.Faq", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaqId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("FaqId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Faqs", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Support.SupportContact", b =>
                {
                    b.Property<int>("SupportContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportContactId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SupportContactId");

                    b.HasIndex("CompanyId");

                    b.ToTable("SupportContacts", (string)null);
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("SkillsetsBackend.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsetsBackend.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.UserPermissionOverride", b =>
                {
                    b.HasOne("SkillsetsBackend.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsetsBackend.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillsetsBackend.Domain.Identity.UserCompanyRole", b =>
                {
                    b.HasOne("SkillsetsBackend.Domain.Identity.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SkillsetsBackend.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
