<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <NoWarn>$(NoWarn);AV0029;AV0030</NoWarn>
    <UserSecretsId>5533a76d-1e3f-45dc-8998-f188ac503b20</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\SkillsetsBackend.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\SkillsetsBackend.Infrastructure.csproj" />
    <ProjectReference Include="..\Domain\SkillsetsBackend.Domain.csproj" />
    <ProjectReference Include="..\Shared\SkillsetsBackend.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.9.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
